# Setup
title:              Articles from StackExpress.com
tagline:            Articles earned from wysdom and experience over years.
description:        Articles earned from wysdom and experience over years.
baseurl:            ""
paginate:           1
locale:             "en"
show_downloads:     false
google_analytics:   G-EM6PMSQZNM
theme:              jekyll-theme-cayman

# About/contact
author:
  name:             Shivam Bajpai
  url:              https://StackExpress.com 

# Gems
gems:
  - jekyll-paginate

# Others
markdown: kramdown

# Site Configs
categories: [devops, developers, git, cicd]

